"""Mock provider - lets the whole pipeline run without an API key.

Produces schema-valid, clearly-labelled placeholder blocks derived from the
file name and (if ffprobe is available) the real duration.
"""
from __future__ import annotations

import json
import re
import time
from typing import Any

from services.ai_gateway.base import RawModelOutput, StageCallback, VideoAnalysisRequest
from services.block_engine.media import probe_duration_seconds, seconds_to_ts


def _title_from_name(name: str) -> str:
    stem = re.sub(r"\.[A-Za-z0-9]+$", "", name)
    stem = re.sub(r"[_\-]+", " ", stem).strip()
    return stem.title() or "Untitled video"


class MockProvider:
    name = "mock"

    def __init__(self, model: str = "mock-v1", delay_seconds: float = 0.4):
        self.model = model
        self.delay = delay_seconds

    def analyze_video(self, request: VideoAnalysisRequest, on_stage: StageCallback) -> RawModelOutput:
        v = request.video
        duration = probe_duration_seconds(v.path) if v.path else None
        end = duration or 300.0
        title = _title_from_name(v.name)
        on_stage("UPLOADED", {"note": "mock provider - nothing was uploaded"})
        time.sleep(self.delay)
        on_stage("ANALYZING", {"model": self.model})
        time.sleep(self.delay)

        third = end / 3
        analysis: dict[str, Any] = {
            "video": {
                "title": f"[MOCK] {title}",
                "video_type": "event",
                "language": "hi-en",
                "description": (
                    "Placeholder analysis generated by the mock provider. Set GEMINI_API_KEY to get a real analysis. "
                    f"Source: {v.name}."
                ),
                "observed_duration": seconds_to_ts(end),
            },
            "events": [
                {
                    "name": f"[MOCK] {title}",
                    "date": None,
                    "venue": "CIMAGE Campus",
                    "organizer": "CIMAGE",
                    "description": "Placeholder event block.",
                    "confidence": 0.5,
                }
            ],
            "people": [
                {"name": "Speaker 1", "role": None, "context": "Placeholder speaker.", "timestamps": [seconds_to_ts(third)], "confidence": 0.5}
            ],
            "transcript": [
                {"speaker": "Speaker 1", "start_time": "00:00:00", "end_time": seconds_to_ts(third), "text": "[MOCK] Placeholder transcript segment one.", "language": "en"},
                {"speaker": "Speaker 1", "start_time": seconds_to_ts(third), "end_time": seconds_to_ts(end), "text": "[MOCK] Placeholder transcript segment two.", "language": "en"},
            ],
            "topics": [
                {"name": "Placeholder topic", "evidence": "Mock provider output.", "timestamps": [seconds_to_ts(third)], "confidence": 0.5}
            ],
            "key_moments": [
                {"timestamp": seconds_to_ts(third * 2), "description": "[MOCK] Placeholder key moment.", "importance": "medium"}
            ],
            "quotes": [
                {"speaker": "Speaker 1", "text": "[MOCK] Placeholder quote.", "timestamp": seconds_to_ts(third), "source_reference": "mock"}
            ],
            "media": [
                {"timestamp": "00:00:05", "description": "[MOCK] Opening frame.", "suitable_for": ["thumbnail"]}
            ],
            "summary": {
                "short_summary": f"[MOCK] Placeholder summary for {title}.",
                "detailed_summary": "This is a placeholder produced without any AI model. Configure GEMINI_API_KEY for real output.",
                "key_points": ["Mock provider active", "Pipeline wiring verified"],
            },
            "content_opportunities": [
                {
                    "title": f"[MOCK] Article idea about {title}",
                    "reason": "Placeholder opportunity.",
                    "suggested_formats": ["blog", "linkedin"],
                    "audience": "prospective students",
                    "confidence": 0.5,
                }
            ],
        }
        out = RawModelOutput(
            text=json.dumps(analysis),
            model=self.model,
            usage={"input_tokens": 0, "output_tokens": 0, "thought_tokens": 0, "total_tokens": 0},
            meta={"duration_seconds": duration},
        )
        for extra in request.extra_passes:
            on_stage("ANALYZING", {"pass": extra.name, "model": self.model})
            people = {"people": [
                {"name": "Voiceover", "role": None, "context": "[MOCK] narrator", "timestamps": ["00:00:00"], "identified_by": "unnamed", "confidence": 1.0},
                {"name": "[MOCK] Known Person", "role": "Director", "context": "[MOCK] recognised in group shot", "timestamps": [seconds_to_ts(third)], "identified_by": "recognised", "confidence": 0.6},
            ]}
            out.extras[extra.name] = RawModelOutput(text=json.dumps(people), model=self.model, usage=dict(out.usage))
        return out

    def repair_json(self, invalid_text: str, error: str, json_schema: dict[str, Any]) -> RawModelOutput:
        # The mock never emits invalid JSON; return the input unchanged so the engine surfaces the error.
        return RawModelOutput(text=invalid_text, model=self.model)

    def describe_images(self, system_instruction: str, prompt: str, images: list[tuple[bytes, str]], json_schema: dict[str, Any], *,
                        model: str | None = None, thinking_level: str | None = None) -> RawModelOutput:
        """Canned shot descriptions: one 'good' tile per 'tile N' mentioned in the prompt, matched to the first block id it finds."""
        tiles = [int(n) for n in re.findall(r"tile (\d+)", prompt)]
        block_ids = re.findall(r"\[id=([^\]]+)\]", prompt)
        out = {"tiles": [
            {"tile": n, "visible": f"[MOCK] still {n}: placeholder description of what is visible", "people": 0,
             "quality": "good" if i % 3 != 2 else "transition", "suitable_for": ["blog_hero"] if i == 0 else ["social_post"],
             "matches_block": block_ids[0] if i == 0 and block_ids else None}
            for i, n in enumerate(dict.fromkeys(tiles))
        ]}
        return RawModelOutput(text=json.dumps(out), model=model or self.model, usage={"input_tokens": 0, "output_tokens": 0, "thought_tokens": 0, "total_tokens": 0})

    def generate_structured(self, system_instruction: str, prompt: str, json_schema: dict[str, Any], *, model: str | None = None, thinking_level: str | None = None) -> RawModelOutput:
        """Canned blog draft that cites the evidence ids it finds in the prompt ([id=...])."""
        ids = [i for i in re.findall(r"\[id=([^\]]+)\]", prompt) if ":" in i]  # real block ids look like job:type:n
        brief = re.search(r"BRIEF:\s*(.+)", prompt)
        title = (brief.group(1).strip() if brief else "Untitled").splitlines()[0][:80]
        draft = {
            "title": f"[MOCK] {title}",
            "slug": re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")[:60] or "mock-draft",
            "seo_title": f"[MOCK] {title} | CIMAGE Patna",
            "meta_description": "Placeholder draft generated by the mock provider for pipeline testing.",
            "excerpt": "Placeholder excerpt.",
            "body_markdown": "## Placeholder section\n\nThis draft was generated without an AI model. " + " ".join(f"Evidence {i} used." for i in ids[:3]),
            "tags": ["CIMAGE Patna", "mock"],
            "citations": [{"block_id": i, "used_for": "placeholder"} for i in ids[:3]] + ([{"block_id": "not-in-evidence", "used_for": "should be dropped"}] if ids else []),
            "hero_block_id": ids[0] if ids else None,
            "social": {"linkedin": "[MOCK] LinkedIn post", "instagram": "[MOCK] Instagram caption", "facebook": "[MOCK] Facebook post"},
            "evidence_gaps": ["mock provider: no real evidence considered"],
        }
        return RawModelOutput(text=json.dumps(draft), model=model or self.model, usage={"input_tokens": 0, "output_tokens": 0, "thought_tokens": 0, "total_tokens": 0})
